%YAML:1.0

init:
  rostopic: /uwb_init/uwb_anchors
  n_fixed_anchors: 2
  n_known_anchors: 0
  min_dist_to_use_uwb: 0.5

tag0:
  rostopic: /uwb_driver_node/uwb
  calib_uwb_extrinsics: false
  p_UinI: [0.01, -0.01, -0.05]
  uwb_sigma_range: 0.5
  prior_uwb_imu_cov: 0.1
  uwb_chi2_multipler: 1.0

anchor0:
  id: 19333
  fix: true
  p_AinG: [2.97,1.44,2.13]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor1:
  id: 22660
  fix: false
  p_AinG: [-2.45,3.75,1.53]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor2:
  id: 19110
  fix: true
  p_AinG: [-0.71,-0.93,0.25]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02

anchor3:
  id: 7435
  fix: false
  p_AinG: [-2.19,-4.16,1.22]
  const_bias: 0.0
  dist_bias: 0.0
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.2
  prior_dist_bias_cov: 0.02
