%YAML:1.0

init:
  rostopic: /uwb_init/uwb_anchors
  n_fixed_anchors: 2
  n_known_anchors: 4

tag0:
  rostopic: /uwb_driver_node/uwb
  calib_uwb_extrinsics: true
  p_UinI: [0.15, 0.2, 0.02]
  uwb_sigma_range: 0.2
  prior_uwb_imu_cov: 0.1
  uwb_chi2_multipler: 1.0

anchor0:
  id: 0
  fix: true
  p_AinG: [0.0, 0.0, 0.0]
  const_bias: 0.1
  dist_bias: 0.3
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.01
  prior_dist_bias_cov: 0.01

anchor1:
  id: 1
  fix: true
  p_AinG: [-3.0, -3.0, 0.0]
  const_bias: 0.1
  dist_bias: 0.3
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.01
  prior_dist_bias_cov: 0.01

anchor2:
  id: 2
  fix: true
  p_AinG: [-12.3, -7, 1.1]
  const_bias: 0.1
  dist_bias: 0.3
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.01
  prior_dist_bias_cov: 0.01

anchor3:
  id: 3
  fix: true
  p_AinG: [-5.0, -9.4, 0.2]
  const_bias: 0.1
  dist_bias: 0.3
  prior_p_AinG_cov: 0.05
  prior_const_bias_cov: 0.01
  prior_dist_bias_cov: 0.01
